### ISSUE TITLE
TypeError: current.toFixed is not a function

### ISSUE THREAD

**Issue by waako** [cflurin/node-red-contrib-ramp-thermostat#8]
Since updating node-red to 0.16.2 I'm now getting the following error in debug tab for my ramp thermostat node:
```
msg : error
"TypeError: current.toFixed is not a function"
```
I assume it is referring to `current = parseFloat((current).toFixed(1));` [on Line 164](https://github.com/cflurin/node-red-contrib-ramp-thermostat/blob/master/ramp-thermostat/ramp-thermostat.js#L164)

I was previously on node-red version 0.15.2 so not sure what has changed which might expose this.

**Comment by cflurin** [comment]
Please, check your input value, it should be a number not a string.

**Comment by waako** [comment]
Doh, my bad thanks, it was being set to number in most places, but the new mqtt input wasn't!

Thanks for pointing out my error.
